### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [ddurham2/rezound#9]
Hi there, 1st of all thanks for your cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO](https://github.com/forart/HyMPS#-) \ [Editors page](https://github.com/forart/HyMPS/blob/main/Aeditors.md#--) \ [Generic subsection](https://github.com/forart/HyMPS/blob/main/Aeditors.md#generic-)), can you please add a "GH-compliant" license file ?

Expliciting licensing terms is extremely important to let other devs (and not only) understand how to reuse/adapt/modify your code in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/ddurham2/rezound/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/ddurham2/rezound/?label=LICENSE)

Anyway you can easily set a "compliant" one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve categorization/sorting of collected projects in order to push their evolution by favouring collaborations between developers (and not only).

Thanks in advance.

**Comment by MarcoRavich** [comment]
Bump (request updated).

**Comment by ddurham2** [comment]
I moved .docs/COPYING to ./LICENSE.  GH seems to be aware that it's the license now.  Did that help on your end?

**Comment by MarcoRavich** [comment]
Hi there, thanks for your intervention but - as you can see from the badge above - the problem seems to be different: if it doesn't cause you any problem, it would be better to completely delete the old license file (which is not compliant for GH) and re-set it via the GH license-wizard.

Thanks again.

**Comment by ddurham2** [comment]
appears to be working now

**Comment by MarcoRavich** [comment]
Yes, thanks !
